version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: isel
      POSTGRES_DB: imsystemdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data